### ISSUE TITLE
can't get combo colors to work w instafade skin

### ISSUE THREAD

**Issue by TidyBog305** [rednir/OsuSkinMixer#115]
combo colors in general only seem to show the first combo color from any given skin but maybe i'm missing something

**Comment by rednir** [comment]
As far as i know its impossible to make an instafade skin that has more than one combo colour, but if you have a skin that proves otherwise let me know.

**Comment by TidyBog305** [comment]
thanks for the info, i don't think i can find any unfortunately :(
