### ISSUE TITLE
Skin.ini not read if capital S. New, incomplete skin.ini is created.

### ISSUE THREAD

**Issue by tarorororororo** [rednir/OsuSkinMixer#117]
When creating or modifying a skin, if the base skin's file is Skin.ini with a capital S, all commands in there will be ignored and a new file, skin.ini with lowercase s, will be created, giving a messed up skin. 

I am using arch linux. This issue may be specific to the linux release, I have not tried on Windows.

**Comment by tarorororororo** [comment]
![image](https://github.com/rednir/OsuSkinMixer/assets/92291273/017f6beb-f3d6-476e-9d57-71656353e110)

**Comment by tarorororororo** [comment]
This subsequently doesn't add files that may be included in the skin. For example, if my number assets are in a num folder, so the skin.ini's line under Fonts would be default: num/default*, it is not parsed and so the newly created skin by the application will not have this num folder with my numbers, since it doesn't know it needs it. It will create the skin without that folder in it.

**Comment by rednir** [comment]
I dont really have a easy way of testing this right now, but this should be fixed in the latest update. Let me know if otherwise
