### ISSUE TITLE
score-x element does not get copied to created skin

### ISSUE THREAD

**Issue by BillyParkerr** [rednir/OsuSkinMixer#12]
The score-x and score-x@2x element do not get copied to the newly created skin. This causes the osu! client to use the default element causing visual problems as shown in the screenshots below. I believe that this element should be taken from the interface skin.

![screenshot011](https://user-images.githubusercontent.com/43602064/140589728-fa294465-dfe0-46d3-be88-766978be4f0e.png)

![screenshot012](https://user-images.githubusercontent.com/43602064/140589805-167a54ac-644e-43e8-949d-d64356db6cab.png)

**Comment by rednir** [comment]
working fine for me.

are you on the latest version? and if so, can you give me a link/name of the interface skin?

**Comment by BillyParkerr** [comment]
Yes have tried on both 1.2 and 1.3. Easy way to recreate the scenario is to create a skin using all elements from [this skin](https://drive.google.com/file/d/1HzoxHiUfTN8Y6p84EIzcwjZrzqJ4K1Nc/view).

**Comment by rednir** [comment]
i still cant reproduce for some reason. its possible the v1.3.1 release may fix it for you if youre willing to give it a shot, but i highly doubt it. i will leave this open and maybe investigate more later.

**Comment by BillyParkerr** [comment]
Yhh seems to be working now not sure why it wasn't working earlier ill close the issue
