### ISSUE TITLE
separate mania keymodes

### ISSUE THREAD

**Issue by breadles5** [rednir/OsuSkinMixer#132]
add support to add keymodes from different skins

just take
```
[Mania]
keys: n
...
```
from one skin and repeat for another skin(s)

**Comment by rednir** [comment]
![image](https://github.com/user-attachments/assets/17e181b1-3bc8-4cee-b920-f1c0a1cd2b2b)

cant you already do this

**Comment by breadles5** [comment]
i didnt even see that, sorry
