### ISSUE TITLE
Instafade can cut off Hitcircles

### ISSUE THREAD

**Issue by limefps** [rednir/OsuSkinMixer#133]
[very_helpful_logs.txt](https://github.com/user-attachments/files/16479157/very_helpful_logs.txt)

On some skins, using the "Instafade Hitcircles" option will cut off part of the hitcircle. This is the case for example with [JesusOmega Planets NM](https://drive.google.com/file/d/1r-yxrwNj2yIhbTHCZ048DdYOIQWNzShZ/view).

Stock 
![stock hitcircle](https://github.com/user-attachments/assets/f14c2fca-66b9-4a59-92b7-8e23eed4cf4e)

Instafaded
![instafaded hitcircle](https://github.com/user-attachments/assets/c63f3a5a-cc7c-46a9-9246-a0274e894b0b)

In this case, (all @2x) the stock hitcircle file is 240x240, default-0 is 100x100 and hitcircleoverlay is 294x294, the instafaded default is 300x300.

There seems to be some kind of issue occuring during a resize, and as a result the circle gets cut off at the extremes.
The error occurs not only with @2x circles, but also at regular size

**Comment by rednir** [comment]
thanks for reporting this bug, it's been fixed in the latest release. just launch osu! skin mixer to update

**Comment by limefps** [comment]
Thanks for the quick fix!
