### ISSUE TITLE
When using the Instafade option on a skin that doesnt include 2x elements skin mixer places generic elements in the skin

### ISSUE THREAD

**Issue by AkiraTenchi** [rednir/OsuSkinMixer#134]
Hey when using the Instafade option on a skin that doesn't include 2x elements skin mixer places generic elements in the skin.
I think a check if 2x elements before applying changes and not randomly including generic 2x elements would be great since rn you need to go into every skin and delete the generic elements manually for the skin to be usable. If more detail is required let me know i can make a video showcasing the issue.

**Comment by AkiraTenchi** [comment]
This is what it looks like rn after instafading 
![Screenshot 2024-08-17 at 17 03 39](https://github.com/user-attachments/assets/dbba49c8-4740-4c0b-8037-4eb17cf2e9d2)
and this is what it is supposed to look like 
![Screenshot 2024-08-17 at 17 04 11](https://github.com/user-attachments/assets/a16585c5-a616-44e2-8c11-f0abe61d561f)

**Comment by AkiraTenchi** [comment]
I assume this could be fixed by just returning 
https://github.com/rednir/OsuSkinMixer/blob/bb3ec26d20e29633185edfccc475408ae2ff4eef/src/Utils/SkinModifierMachine.cs#L249
and here

**Comment by rednir** [comment]
Fixed in the latest release, launch osu! skin mixer to update
