### ISSUE TITLE
skin.ini for copy of skins are incorrect if name option contains brackets

### ISSUE THREAD

**Issue by MF-JEWM** [rednir/OsuSkinMixer#135]
[very_helpful_logs.txt](https://github.com/user-attachments/files/16660846/very_helpful_logs.txt)

Provide details about the bug below:

When modifying a skin, you are given the option to make a copy of it. The skin.ini file that is generated for the copy bugs and turns any option containing brackets into a new section, leading to certain settings not getting properly read by the game when using those skin copies.

| Original skin.ini	                           | Copied skin.ini 	                            |
| ----------------------------------- | ----------------------------------- |
| <img src="https://github.com/user-attachments/assets/620dc7f4-2526-4338-9665-9cad198e8496" height="480" alt="original skin.ini"> | <img src="https://github.com/user-attachments/assets/0268edfb-74f0-468d-bfd5-f6cd0146f7f4" height="480" alt="copied skin.ini"> |

Notice that when the skin with the name option of `- Seoul v11 - [Test]` is copied it it creates a new section in the skin.ini called `[Test]`, or whatever bracketed text is there, which leads to the settings not being processed, since it expects them to be under the `[General]` section

**Comment by rednir** [comment]
Fixed in the latest release, launch osu! skin mixer to update
