### ISSUE TITLE
Does not set Hitcircle overlap correctly when instafading some skins

### ISSUE THREAD

**Issue by AkiraTenchi** [rednir/OsuSkinMixer#136]
Hey sorry to be creating the next issue minutes after the release that fixed my last one but i am experiencing that with some skins the hit circle overlap is not being set correctly when instafading them. Leading to double digit numbers looking as follows:
![Screenshot 2024-08-26 at 20 16 21](https://github.com/user-attachments/assets/f4fab9ba-6fef-4871-bc6f-1e969df6f090)

it is fixable by manually setting:
`[Fonts]
HitCircleOverlap: 160`

I am however not sure what causes this to happen since it seems to happen without recognizable pattern but if it happens with a skin it always happens with that skin. 
This is one of the skins that it happens with but it did also happen with some rafis skins and others https://skins.osuck.net/skins/303?v=0
if you need more examples or information let me know.

**Comment by rednir** [comment]
Pushed out a fix, hopefully there are no more issues with instafade, otherwise please let me know. I tested a few skins and didn't see anything strange so hopefully everythings good now

**Comment by AkiraTenchi** [comment]
Thank you very much, as someone that uses this Software almost daily this is highly appreciated :D

**Comment by rednir** [comment]
You are very welcome, thank you for your appreciation 😄
