### ISSUE TITLE
Score not appearing correctly

### ISSUE THREAD

**Issue by Cadonis0** [rednir/OsuSkinMixer#19]
This also happens for example where it should appear the RPM under a spinner

![image](https://user-images.githubusercontent.com/58173529/140657076-65c58f8f-34f1-452b-aa57-59614f59f996.png)

**Comment by rednir** [comment]
what skin is being used for interface?

**Comment by Cadonis0** [comment]
Varvalian 2019-06-25

**Comment by rednir** [comment]
please try again, this should be fixed!
