### ISSUE TITLE
Mod selection stayed default 

### ISSUE THREAD

**Issue by Rashbel** [rednir/OsuSkinMixer#29]
Sorry, couldn't find "%localappdata%/osu-skin-mixer/log.txt"

https://user-images.githubusercontent.com/57320622/141169947-0d6406ca-43b5-4350-9b66-f626d94e1139.mp4

**Comment by rednir** [comment]
Please redownload the latest release, looks like you were unlucky and downloaded it in the 30 minute window this bug existed for lol

**Comment by rednir** [comment]
oooooops turns out i never fixed the issue. its fixed now in 1.6.1, sorry about that, should really test more thoroughly
