### ISSUE TITLE
.osu-skin-mixer_working-skin

### ISSUE THREAD

**Issue by Zxunivent** [rednir/OsuSkinMixer#35]
Something went wrong.

One or more errors occurred. (Length can not be less than zero. Parameter name : Length)

**Comment by rednir** [comment]
please upload logs

 1. open osu! skin mixer
 2. enable the "log to file" option in the "options" menu at the top
 3. reproduce the issue (make the error appear again)
 4. drag and drop the file at "%localappdata%/osu-skin-mixer/log.txt" into here.

**Comment by rednir** [comment]
no longer relevant
