### ISSUE TITLE
Scrolling Skins

### ISSUE THREAD

**Issue by Chapherino** [rednir/OsuSkinMixer#37]
I have a lot of skins so I should scroll down to see all of them on the list to choose the features. Problem is my scrolling wheel is broken so there are some skins I can't reach except I change their name so they show up on top. Adding a scrolling bar or a click and drag feature could solve this pretty easily I think

**Comment by rednir** [comment]
this will be added in the next update

for now either search for the skin by typing with the keyboard, or resize the window as large as you can
