### ISSUE TITLE
Ability to change specific things

### ISSUE THREAD

**Issue by MenZiiiZ** [rednir/OsuSkinMixer#48]
as the title says, you can do like an advanced mode where you can change specific things in the skin

**Comment by rednir** [comment]
please be more descriptive.you can already customise each file and skin.ini option, what exactly would be in the advanced mode?

**Comment by MenZiiiZ** [comment]
nevermind i just found out how to do it, sorry if i wasted your time, good software tho :D

**Comment by rednir** [comment]
no worries and thank you!

**Comment by MenZiiiZ** [comment]
um, idk actually

**Comment by MenZiiiZ** [comment]
oh wait i can close it
