### ISSUE TITLE
Save settings and refresh skin folder

### ISSUE THREAD

**Issue by SimonDiamond** [rednir/OsuSkinMixer#7]
Hi! First of all, this is an amazing program! So far, I only have 2 issues.
1. There is currently no way to make the program refresh the skin folder for new skins you've added while the program is being open, which forces you to restart to get the new skins, which leads to another problem
2. If your osu folder is in a diffrent location than the one that the program defaults to, it asks you every time you start up the program to select your skin folder

**Comment by rednir** [comment]
both issues will be resolved in the next update

thanks for letting me know!
