### ISSUE TITLE
Fix error when moving between drives

### ISSUE THREAD

**Issue by Flapczek** [rednir/OsuSkinMixer#70]
When i'm creating a skin i'm getting error

[godot.log](https://github.com/rednir/OsuSkinMixer/files/10891792/godot.log)

**Comment by rednir** [comment]
Thanks for reporting the issue, it will be fixed in release v2.2. Until then, you can:
 - manually copy the folder at `%localappdata%/Temp/.osu-skin-mixer_working-skin` to your osu skins folder
 - use [release v1.8.4](https://github.com/rednir/OsuSkinMixer/releases/tag/v1.8.4) instead
