### ISSUE TITLE
Expected a section name Error

### ISSUE THREAD

**Issue by T1nG3R** [rednir/OsuSkinMixer#8]
While importing from azer8#dawn skin.ini this error occurs. 
![зображення](https://user-images.githubusercontent.com/46874273/140554539-c5f0591d-7839-4c89-baac-054499aadce9.png)
skin.ini: https://pastebin.com/r7c0XvPA

**Comment by rednir** [comment]
to get this working you can change line 1 from `¬[General]` to `[General]`

a proper fix will be coming as well, thank you for letting me know
